[project]
name = "mcp-tutorial"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "fastapi-mcp>=0.4.0",
    "fastmcp>=2.12.4",
    "loguru>=0.7.3",
    "uvicorn[standard]>=0.37.0",
]
